replicaCount: 1

imagePullPolicy: Always
## Annotations to be added to Pinpoint Web pods
##
podAnnotations: {}
## Pod affinity
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## Node tolerations for node-exporter scheduling to nodes with taints
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
##
tolerations: []
  # - key: "key"
  #   operator: "Equal|Exists"
  #   value: "value"
  #   effect: "NoSchedule|PreferNoSchedule|NoExecute(1.6 only)"

# Configuration for web UI service
service:
  ui:
    type: "ClusterIP"
    nodePort:
    clusterIP:

# Configuration for Docker Image 
image:
  repository: pinpointdocker/pinpoint-web
  tag: 2.4.1

profiles: release, batch
serverPort: 8079
clusterEnable: true

adminPassword: admin
sendUsage: false
loggingLevelRoot: INFO
showApplicationStat: true

batch:
  enable: false
  server: 127.0.0.1
  flink: 127.0.0.1

mail:
  server:
    url: smtp.gmail.com
    port: 587
    username: username
    password: password
  sender: pinpoint_operator@pinpoint.com
  transportProtocol: smtp
  debug: false
  smtp:
    port: 25
    auth: false
    startTls:
      enable: false
      required: false