apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pinpoint-collector.fullname" . }}
  labels:
{{ include "pinpoint-web.labels" . | indent 4 }}
data:
  CLUSTER_ENABLE:  "{{ .Values.clusterEnable }}"
  PINPOINT_ZOOKEEPER_ADDRESS: "{{ include "pinpoint-collector.zookeeper.fullname" . }}"
  SPRING_PROFILES: "{{ .Values.profiles }}"
  JAVA_OPTS: "-Dspring.profiles.active={{ .Values.profiles }}"
  LOGGING_LEVEL_ROOT:  "{{ .Values.loggingLevelRoot }}"
  FLINK_CLUSTER_ENABLE:  "{{ .Values.flink.enable }}"
  FLINK_CLUSTER_ZOOKEEPER_ADDRESS: "{{ include "pinpoint-collector.zookeeper.fullname" . }}"