replicaCount: 1
## Annotations to be added to Pinpoint Web pods
##
podAnnotations: {}
## Pod affinity
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## Node tolerations for node-exporter scheduling to nodes with taints
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
##
tolerations: []
  # - key: "key"
  #   operator: "Equal|Exists"
  #   value: "value"
  #   effect: "NoSchedule|PreferNoSchedule|NoExecute(1.6 only)"

# Configuration for Docker Image 
image:
  repository: pinpointdocker/pinpoint-collector
  tag: 2.5.2
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "512Mi"
    cpu: "256m"

receiver:
  grpc:
    agentPort: 9991
    statPort: 9992
    spanPort: 9993
  thrift:
    basePort: 9994
    statPort: 9995
    spanPort: 9996
  
profiles: release
loggingLevelRoot: INFO
clusterEnable: true
zookeeper:
  # headless service: pinpoint-zookeeper-headless
  host: pinpoint-zookeeper
flink:
  enabled: true
